config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount Blazer::Engine, at: "blazer"

  root 'admin/lab_forum#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :names, only: [:create]
    end
  end

  scope "(:locale)", locale: /en|zh-TW/ do
    devise_for :users

    # 慣例：名字後須 +s
    scope module: 'admin' do
      resources :lab_forum do
        resources :comments
        get 'status', on: :member

        resources :likes, only: [:create]
      end
    end

    root 'lab_forum#index'

    scope module: 'assignment' do
      # resources :todolists do
      #   get 'status', on: :member
      # end

      # https://stackoverflow.com/questions/19189415/how-may-two-routes-with-different-http-request-types-share-the-same-name
      get "/todolists/:id/status", to: "todolists#status", as: "status_todolist"
      get  "/todolists", to: "todolists#index", as: "todolists"
      post "/todolists", to: "todolists#create"
      get  "/todolists/new", to: "todolists#new", as: "new_todolist"
      get  "/todolists/:id/edit", to: "todolists#edit", as: "edit_todolist"
      get  "/todolists/:id", to: "todolists#show", as: "todolist"
      patch "/todolists/:id", to: "todolists#update"
      delete "/todolists/:id", to: "todolists#destroy"

      root 'todolists#index', to: ""
    end

    # constraints subdomain: 'admin' do
    #   scope module: 'admin' do
    #     resources :lab_forum do
    #       resources :comments
    #       get 'status', on: :member
    #     end
    #     root 'lab_forum#index'
    #   end
    # end

    # constraints subdomain: 'assignment' do
    #   scope module: 'assignment' do
    #     resources :todolists
    #     root 'todolists#index'
    #   end
    # end

    # 高見龍老師的範例
    get 'bmi', to: "bmi#index"
    post 'bmi', to: "bmi#result"

    # get, post自己寫
    get 'name', to: "name#index"
    post 'name', to: "name#post_result"
    get 'username', to: "name#get_result"

    # 靜態網頁
    get 'card', to: "card#show"

    # sinatra (先放著)
    # mount Api::Ping => '/api/ping'

    # 寫在最後一行
    # 基本routes應用：https://railsbook.tw/chapters/11-routes.html
    get "/:single_page" , to: "staticpages#show", as: 'page'
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :bigint           not null, primary key
#  commentable_type :string(255)
#  content          :text(65535)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  commentable_id   :bigint
#  user_id          :bigint
#
# Indexes
#
#  index_comments_on_commentable_type_and_commentable_id  (commentable_type,commentable_id)
#  index_comments_on_user_id                              (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  # 非多型的寫法
  # belongs_to :lab_forum

  has_one_attached :cover
  has_many :likes
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_user!
  def new
    @lab_forum = LabForum.find_by(id: params[:lab_forum_id])
    @comment = Comment.new
  end

  def create
    @lab_forum = LabForum.find_by(id: params[:lab_forum_id])
    @comment = @lab_forum.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
    if @comment.save
      # 問題：按鈕處於submitting...狀態
      # redirect_back(fallback_location: fallback_location)
      redirect_to lab_forum_path(@lab_forum)
    else
      flash.now[:danger] = "error"
      redirect_back(fallback_location: lab_forum_path(@lab_forum))
    end
  end

  def destroy
    @lab_forum = LabForum.find_by(id: params[:id])
    @comment = @lab_forum.comments.find_by(commentable_id: params[:id])
    @comment.destroy
    redirect_to lab_forum_path
  end

  private
  def comment_params
    params[:comment].permit(:content, :cover)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <hr>
          <%= link_to del_p_mark(fa_icon "trash"), lab_forum_comment_path(@lab_forum),
              method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
          <strong><%= User.find_by(id: comment.user_id).username.capitalize %></strong>
            &nbsp;&nbsp;&nbsp;
            Posted at <%= distance_of_time_in_words(comment.commentable.created_at, comment.created_at) %>
           <br/><%= simple_format(comment.content) %>
           <br/><%= image_tag comment.cover if comment.cover.attached? %>
        </p>
      </div>
    </div>

  </article>

</div>

app/views/admin/comments/_form.html.erb
<div class="card my-4">
  <h5 class="card-header">Leave a Comment:</h5>
  <div class="card-body">
      <div class="form-group">
        <%= form_for @comment, url: lab_forum_comments_path(@lab_forum), html: {method: "post"} do |f| %>
          <div class="group">
            <%= f.text_area :content, size: "50x5", placeholder: "Make an offer ", :maxlength=>"254" %><br />
            <p><%= f.label 'Image' %>&nbsp;&nbsp;
               <br/><%= f.file_field(:cover, accept: 'image/png,image/gif,image/jpeg') %>
            </p>
          </div>
          <div class="group"><%= f.submit "Submit", data: { disable_with: "Submitting..." }, class: 'btn btn-primary' %></div>
        <% end %>
      </div>
  </div>
</div>