config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount Blazer::Engine, at: "blazer"

  root 'admin/lab_forum#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :names, only: [:create]
    end
  end

  scope "(:locale)", locale: /en|zh-TW/ do
    devise_for :users

    # 慣例：名字後須 +s
    scope module: 'admin' do
      resources :lab_forum do
        resources :comments
        get 'status', on: :member

        resources :likes, only: [:create]
      end
    end

    root 'lab_forum#index'

    scope module: 'assignment' do
      # resources :todolists do
      #   get 'status', on: :member
      # end

      # https://stackoverflow.com/questions/19189415/how-may-two-routes-with-different-http-request-types-share-the-same-name
      get "/todolists/:id/status", to: "todolists#status", as: "status_todolist"
      get  "/todolists", to: "todolists#index", as: "todolists"
      post "/todolists", to: "todolists#create"
      get  "/todolists/new", to: "todolists#new", as: "new_todolist"
      get  "/todolists/:id/edit", to: "todolists#edit", as: "edit_todolist"
      get  "/todolists/:id", to: "todolists#show", as: "todolist"
      patch "/todolists/:id", to: "todolists#update"
      delete "/todolists/:id", to: "todolists#destroy"

      root 'todolists#index', to: ""
    end

    # constraints subdomain: 'admin' do
    #   scope module: 'admin' do
    #     resources :lab_forum do
    #       resources :comments
    #       get 'status', on: :member
    #     end
    #     root 'lab_forum#index'
    #   end
    # end

    # constraints subdomain: 'assignment' do
    #   scope module: 'assignment' do
    #     resources :todolists
    #     root 'todolists#index'
    #   end
    # end

    # 高見龍老師的範例
    get 'bmi', to: "bmi#index"
    post 'bmi', to: "bmi#result"

    # get, post自己寫
    get 'name', to: "name#index"
    post 'name', to: "name#post_result"
    get 'username', to: "name#get_result"

    # 靜態網頁
    get 'card', to: "card#show"

    # sinatra (先放著)
    # mount Api::Ping => '/api/ping'

    # 寫在最後一行
    # 基本routes應用：https://railsbook.tw/chapters/11-routes.html
    get "/:single_page" , to: "staticpages#show", as: 'page'
  end
end

app/models/lab_forum.rb
# == Schema Information
#
# Table name: lab_forums
#
#  id          :bigint           not null, primary key
#  category    :string(255)
#  click       :integer          default(0)
#  description :text(65535)
#  question    :string(255)
#  solved      :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class LabForum < ApplicationRecord
  include Recount

  CATEGORY = ['qa','chat','others'].freeze

  # has_many :comments, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :expressable, dependent: :destroy

  belongs_to :user
end

app/controllers/admin/lab_forum_controller.rb
class Admin::LabForumController < ApplicationController
  # layout "admin"
  before_action :find_labforum, only: [:edit, :update, :destroy, :show, :status]
  before_action :authenticate_user!
  # before_action :required # 若非後台人員，即會出現登入阻擋
  def index
    @lab_forums = LabForum.all.order(id: :desc)
  end

  def new
    @lab_forum = LabForum.new
  end

  def create
    @lab_forum = LabForum.new(labforum_params)
    @lab_forum.user = current_user  # 如果沒有這行，會有:user=>["must exist"]的錯誤提示
    if @lab_forum.save
      respond_to :js
      # redirect_to lab_forum_index_path, notice: "新增成功!"
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comment.commentable = @lab_forum
    @comment.user = current_user

    # @comment.content = "123"
    # @comment.save
  end

  def edit
  end

  def destroy
    @lab_forum_id = @lab_forum.id
    @lab_forum.destroy if @lab_forum

    # 會自動找 destroy.js.erb
    # respond_to do |format|
    #   format.js
    # end

    # 舊 code
    # redirect_to lab_forum_index_path, notice: "已刪除!"
  end

  def update
    if @lab_forum.update(labforum_params) # 成功
      redirect_to lab_forum_index_path, notice: "更新成功!"
    else
      render :edit # 失敗
    end
  end

  def status
    @id = params[:id]

    if user_signed_in? && (@lab_forum.user == current_user)
      status = @lab_forum.solved.eql?(false) ? true : false
      @lab_forum.update(solved: status)
    end

    respond_to do |format|
      format.js {render 'status'}
    end
  end

  private
  def labforum_params
    params.require(:lab_forum).permit(:question, :description, :category, :solved)
  end

  def find_labforum
    @lab_forum = LabForum.find_by(id: params[:id])
  end
end

app/helpers/admin/lab_forum_helper.rb
module Admin::LabForumHelper
  # 改變狀態
  def solved_monitor(bool)
    if bool
      fa_icon "check 2x", right: true
    else
      fa_icon "times 2x", right: true
    end
  end

  # 把<p>...</p>元素去除
  def del_p_mark(str)
    str.gsub(/<p>.*<\/p>/, '').html_safe
    # 網站：https://www.rubyguides.com/2019/07/ruby-gsub-method/
    # 網站：https://stackoverflow.com/questions/52853995/replacing-html-tag-and-its-content-using-ruby-gsub
  end

  # 判斷是否已經按讚
  def clicked(lab_forum_id)
    LabForum.find_by(id: lab_forum_id).likes.present?
  end
end

app/views/admin/lab_forum/_card.html.erb
<div class="col-6 col-md-4 col-sm-12" id="card_<%= article.id %>">
    <div class="card">
      <img class="card-img-top" src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1200&q=80"
          alt="Card image cap">
      <div class="card-body">
        <div class="d-flex">
          <div class="mr-auto p-2">
            <h5 class="card-title">
              <%= article.question.capitalize %>
            </h5>
          </div>
          <div class="p-2">
            <% if article.solved == false %>
              <%= link_to 'Open', status_lab_forum_path(article), remote: true,
                  class: 'btn btn-success btn-sm', id: "card-btn-#{article.id}" %>
            <% else %>
              <%= link_to 'Closed', status_lab_forum_path(article), remote: true,
                  class: 'btn btn-danger btn-sm', id: "card-btn-#{article.id}" %>
            <% end %>
          </div>
        </div>

        <div class="d-flex">
          <div class="p-2">User: <%= article.user.username.capitalize %></div>
          <div class="ml-auto p-2">
            <% if clicked(article.id) %>
              <%= link_to (fa_icon "thumbs-up"), lab_forum_likes_path(article),
                  { method: :post,
                    class: 'thumb-clicked',
                    id: "like-btn-#{article.id}",
                    remote: true
                    } %>
            <% else %>
              <%= link_to (fa_icon "thumbs-up"), lab_forum_likes_path(article),
                  { method: :post,
                    id: "like-btn-#{article.id}",
                    class: 'thumb',
                    remote: true
                    } %>
            <% end %>

          </div>
        </div>

        <p class="card-text">
          <small class="text-muted">
            <span class="icon"><i class="fa fa-eye"></i></span>
            <span class="vote_count">?</span>&emsp;
            <% if clicked(article.id) %>
              <span class="icon"><i class="fa fa-heart heart_clicked" id="heart-<%= article.id %>"></i></span>
            <% else %>
              <span class="icon"><i class="fa fa-heart" id="heart-<%= article.id %>"></i></span>
            <% end %>
            <span class="vote_count" id="like-num-<%= article.id %>">
              <%= LabForum.find_by(id: article.id).click %>
            </span>&emsp;
            <span class="icon"><i class="fa fa-comment"></i></span>
            <span class="vote_count">?</span>
          </small>
        </p>

      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated at
          <%= distance_of_time_in_words(article.updated_at, Time.current) %>
        </small><br/>
        <small class="text-muted">
          <% if user_signed_in? && ( article.user == current_user ) %>
            <%= link_to (fa_icon "eye"), lab_forum_path(article) %>&emsp;
            <%= link_to (fa_icon "edit"), edit_lab_forum_path(article) %>&emsp;
            <%= link_to (fa_icon "trash"), lab_forum_path(article), remote: true,
                  method: "delete", data: { confirm: "Are you sure?" } %>
          <% else %>
            <%= link_to (fa_icon "eye"), lab_forum_path(article) %>
          <% end %>
        </small>
      </div>
    </div>
  </div>

app/views/admin/lab_forum/_cards.html.erb
<div class="card-group" id="card_forums">
  <% @lab_forums.each do |article| %>
    <%= render 'card', article: article %>
  <% end %>
</div>

app/views/admin/lab_forum/_edit_modal.html.erb
<div class="modal fade" id="edit_forum">
  <%= simple_form_for(form_type, url: url, remote: true) do |f| %>
    <div class="modal-dialog mw-100 w-75">
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" style="color:#737373;font-style:italic"><%= t('lab_forum.edit_question') %></h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <%= f.input :question %>
          <%= f.input :description, as: :ckeditor, input_html: { ckeditor: { height: 400 } } %>
          <%= f.input :category, as: :radio_buttons, collection: LabForum::CATEGORY, wrapper: :horizontal_collection_inline %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Submit", data: { disable_with: "Submitting..." }, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/lab_forum/_form.html.erb
<div class="row">
  <div class="col-8">
    <div  class="group"><h2><%= title %></h2></div>
      <%= simple_form_for @lab_forum, url: url do |f| %>
        <%= f.input :question %>
        <%= f.input :description, as: :ckeditor, input_html: { ckeditor: { height: 400 } } %>
        <%= f.input :category, as: :radio_buttons, collection: LabForum::CATEGORY, wrapper: :horizontal_collection_inline %>
        <%= f.submit "Submit", data: { disable_with: "Submitting..." }, class: 'btn btn-primary' %>
      <% end %>
      <%= link_to 'Back', lab_forum_index_path, class: 'btn' %>
    </div>
  <div class="col-4">
</div>

<%# text 大小參考網址：https://stackoverflow.com/questions/13556522/cant-change-the-height-of-a-text-field-in-simple-form %>
<%# simple-form 參考網址：http://simple-form-bootstrap.plataformatec.com.br/documentation %>

app/views/admin/lab_forum/_list.html.erb
<tr id="<%= article.id %>">
  <td>
    <% if article.solved == false %>
      <%= link_to 'Open', status_lab_forum_path(article), remote: true, class: 'btn btn-success', id: "btn-#{article.id}" %>
    <% else %>
      <%= link_to 'Closed', status_lab_forum_path(article), remote: true, class: 'btn btn-danger', id: "btn-#{article.id}" %>
    <% end %>
  </td>
  <td class="q"><%= article.question %></td>
  <td class="user"><%= User.find_by(id: article.user_id).username.capitalize %></td>
  <td class="category"><%= article.category %></td>
  <td>
    <% if user_signed_in? && ( article.user == current_user ) %>
      <%= link_to (fa_icon "eye"), lab_forum_path(article), remote: true, class: 'btn' %>
      <%= link_to (fa_icon "edit"), edit_lab_forum_path(article), remote: true, class: 'btn' %>
      <%= link_to (fa_icon "trash"), lab_forum_path(article), remote: true,
            method: "delete", data: { confirm: "Are you sure?" }, class: 'btn'  %>
    <% else %>
      <%= link_to (fa_icon "eye"), lab_forum_path(article), class: 'btn' %>
    <% end %>
  </td>
  <td class="create"><%= article.created_at.to_s[0..-4] %></td>
  <td class="update"><%= article.updated_at == article.created_at ? "---" : article.updated_at.to_s[0..-4] %></td>
</tr>

app/views/admin/lab_forum/_lists.html.erb
<table class="table">
  <thead>
    <tr>
      <td><%= t('lab_forum.status') %></td>
      <td><%= t('lab_forum.problem') %></td>
      <td><%= t('lab_forum.author') %></td>
      <td><%= t('lab_forum.category') %></td>
      <td><%= t('lab_forum.action') %></td>
      <td><%= t('lab_forum.create_time') %></td>
      <td><%= t('lab_forum.update_time') %></td>
    </tr>
  </thead>
  <tbody id='lab_forums'>
    <% @lab_forums.each do |article| %>
      <%= render 'list', article: article %>
    <% end %>
  </tbody>
</table>

app/views/admin/lab_forum/_modal.html.erb
<%= simple_form_for(form_type, url: url, remote: true) do |f| %>
  <div class="modal-dialog mw-100 w-75">
    <div class="modal-content">
      <div class="modal-header">
          <h4 class="modal-title" style="color:#737373;font-style:italic"><%= t('lab_forum.new_question') %></h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= f.input :question %>
        <%= f.input :description, as: :ckeditor, input_html: { ckeditor: { height: 400 } } %>
        <%= f.input :category, as: :radio_buttons, collection: LabForum::CATEGORY, wrapper: :horizontal_collection_inline %>
      </div>
      <div class="modal-footer">
        <%= f.submit "Submit", data: { disable_with: "Submitting..." }, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/lab_forum/create.js.erb
$('#card_forums').prepend('<%= j render 'card', article: @lab_forum %>');
$('#forum-modal').modal('hide');

app/views/admin/lab_forum/destroy.js.erb
$('#<%= @lab_forum_id %>').slideUp();
$('#card_<%= @lab_forum_id %>').slideUp();

app/views/admin/lab_forum/edit.js.erb
$('#remote-container').html('<%= j render 'edit_modal', form_type: @lab_forum, url: lab_forum_path %>');
$('#edit_forum').modal('show');

app/views/admin/lab_forum/index.html.erb
<% content_for :page_title,  "lab_forum" %>

<div class="container">
  <h1><%= t('lab_forum.all_qs') %></h1>
  <h4><%= link_to t('lab_forum.add_q'), '#forum-modal', data: {toggle: 'modal'}, class: 'btn btn-link' %></h4>
  <%= render 'cards' %>
</div>

<div class="modal fade" id="forum-modal">
  <%= render 'modal', form_type: LabForum.new, url: lab_forum_index_path %>
</div>

app/views/admin/lab_forum/show.html.erb
<section class="section example">
<body>
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <!-- Post Content Column -->
      <div class="col-lg-8">
        <!-- Title -->
        <h1 class="mt-4"><%= @lab_forum.question %></h1>
        <!-- Author -->
        <p class="lead">
          by
          <a href="#"><%= User.find_by(id: @lab_forum.user_id).username.capitalize %></a>
        </p>
        <hr>
        <!-- Date/Time -->
        <p>Posted on <%= @lab_forum.created_at.to_s[0..-4] %></p>
        <% if @lab_forum.solved == false %>
          <%= link_to 'Open', status_lab_forum_path(@lab_forum), remote: true, class: 'btn btn-success', id: "btn-#{@lab_forum.id}" %>
        <% else %>
          <%= link_to 'Closed', status_lab_forum_path(@lab_forum), remote: true, class: 'btn btn-danger', id: "btn-#{@lab_forum.id}" %>
        <% end %>
        <!-- Default checked -->
        <hr>
        <!-- Post Content -->
        <p class="lead"><%= simple_format @lab_forum.description %></p>

        <blockquote class="blockquote">
          <p class="mb-0">No pain, no gain.</p>
          <footer class="blockquote-footer">No money.
            <cite title="Source Title">～</cite>
          </footer>
        </blockquote>
        <hr>
        <%= render "admin/comments/form" %>
        <%= render :partial => @comment, collection: @lab_forum.comments.reverse %>


      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search（尚未開放）</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories（尚未開放）</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

app/views/admin/lab_forum/status.js.erb
var status = "<%= @lab_forum.solved %>";
var auth = "<%= user_signed_in? && ( @lab_forum.user == current_user ) %>";

if( auth == 'true' ){
  if( status == 'false' ){
    // $("#btn-<%= @id %>")[0].innerHTML = ('Open');
    // $("#btn-<%= @id %>").removeClass('btn-danger');
    // $("#btn-<%= @id %>").addClass('btn-success');
    $("#card-btn-<%= @id %>")[0].innerHTML = ('Open');
    $("#card-btn-<%= @id %>").removeClass('btn-danger');
    $("#card-btn-<%= @id %>").addClass('btn-success');
  }else{
    // $("#btn-<%= @id %>")[0].innerHTML = ('Closed');
    // $("#btn-<%= @id %>").removeClass('btn-success');
    // $("#btn-<%= @id %>").addClass('btn-danger');
    $("#card-btn-<%= @id %>")[0].innerHTML = ('Closed');
    $("#card-btn-<%= @id %>").removeClass('btn-success');
    $("#card-btn-<%= @id %>").addClass('btn-danger');
  }
}else{
  alert("This is not your question.\nYou don't have permission.");
}

app/views/admin/lab_forum/update.js.erb
$('#card_<%= article.id %>').replaceWith('<%= j render 'card', article: @lab_forum %> %>');