config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount Blazer::Engine, at: "blazer"

  root 'admin/lab_forum#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :names, only: [:create]
    end
  end

  scope "(:locale)", locale: /en|zh-TW/ do
    devise_for :users

    # 慣例：名字後須 +s
    scope module: 'admin' do
      resources :lab_forum do
        resources :comments
        get 'status', on: :member

        resources :likes, only: [:create]
      end
    end

    root 'lab_forum#index'

    scope module: 'assignment' do
      # resources :todolists do
      #   get 'status', on: :member
      # end

      # https://stackoverflow.com/questions/19189415/how-may-two-routes-with-different-http-request-types-share-the-same-name
      get "/todolists/:id/status", to: "todolists#status", as: "status_todolist"
      get  "/todolists", to: "todolists#index", as: "todolists"
      post "/todolists", to: "todolists#create"
      get  "/todolists/new", to: "todolists#new", as: "new_todolist"
      get  "/todolists/:id/edit", to: "todolists#edit", as: "edit_todolist"
      get  "/todolists/:id", to: "todolists#show", as: "todolist"
      patch "/todolists/:id", to: "todolists#update"
      delete "/todolists/:id", to: "todolists#destroy"

      root 'todolists#index', to: ""
    end

    # constraints subdomain: 'admin' do
    #   scope module: 'admin' do
    #     resources :lab_forum do
    #       resources :comments
    #       get 'status', on: :member
    #     end
    #     root 'lab_forum#index'
    #   end
    # end

    # constraints subdomain: 'assignment' do
    #   scope module: 'assignment' do
    #     resources :todolists
    #     root 'todolists#index'
    #   end
    # end

    # 高見龍老師的範例
    get 'bmi', to: "bmi#index"
    post 'bmi', to: "bmi#result"

    # get, post自己寫
    get 'name', to: "name#index"
    post 'name', to: "name#post_result"
    get 'username', to: "name#get_result"

    # 靜態網頁
    get 'card', to: "card#show"

    # sinatra (先放著)
    # mount Api::Ping => '/api/ping'

    # 寫在最後一行
    # 基本routes應用：https://railsbook.tw/chapters/11-routes.html
    get "/:single_page" , to: "staticpages#show", as: 'page'
  end
end

app/controllers/assignment/todolists_controller.rb
class Assignment::TodolistsController < ApplicationController
  # layout "admin"

  before_action :find_todos, only: [:edit, :update, :destroy, :show, :status]
  # before_action :authenticate_user!

  # 若非後台人員，即會出現登入阻擋
  # before_action :required

  def index
    @todos = Todo.all.order(id: :desc)
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    # @todo.user = current_user
    # 如果沒有這行，會有:user=>["must exist"]的錯誤提示
    if @todo.save
      redirect_to todolists_path, notice: "新增成功!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @todo.destroy if @todo
    redirect_to todolists_path, notice: "已刪除!"
  end

  def update
    if @todo.update(todo_params) # 成功
      redirect_to todolists_path, notice: "更新成功!"
    else
      render :edit # 失敗
    end
  end

  # def status
  #   @id = params[:id]

  #   if @todo.solved.eql? false
  #     @todo.update(solved: true)
  #   elsif
  #     @todo.update(solved: false)
  #   end

  #   respond_to do |format|
  #     format.js {render 'status'}
  #   end
  # end

  def status
    @id = params[:id]

    if @todo.status.eql? false
      @todo.update(status: true)
    elsif
      @todo.update(status: false)
    end

    respond_to do |format|
      format.js {render 'status'}
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:content, :complete_time, :status, :priority)
  end

  def find_todos
    @todo = Todo.find_by(id: params[:id])
  end
end

app/helpers/assignment/todos_helper.rb
module Assignment::TodosHelper
  def complete_time(time)
    return 'None' if time.eql? nil

    time
  end
end

app/views/assignment/todolists/_form.html.erb
<script>
  $(function () {
    $('.datepicker').datetimepicker({
      format: 'YYYY-MM-DD HH:mm:ss'
    });
  });
</script>

<div class="row">

  <div class="col-sm-6">
    <div  class="group"><h2><%= title %></h2></div>
    <%= simple_form_for @todo, url: url do |f| %>
      <%= f.input :content, input_html: {value: f.object.content || 'Default Content'} %>
      <%= f.input :priority, collection: Todo.priorities, prompt: true %>
      <div class="input-group" data-target-input="nearest">
          <%= f.text_field :complete_time, id: "complete_time", class: "form-control datepicker", data: { target: '#complete_time'} %>
          <div class="input-group-append" data-target="#complete_time" data-toggle="datetimepicker">
              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
      </div>

      <%= f.submit 'Submit', data: { disable_with: "Submitting..." }, class: 'btn btn-primary' %>
      <%= link_to 'Back', todolists_path, class: 'btn' %>
    <% end %>
  </div>

  <div class="col-sm-6">
  </div>

</div>

app/views/assignment/todolists/edit.html.erb
<% content_for :page_title,  "assignment: Edit" %>

<div class="container-fluid">
  <script>
    $(function () {
      $('.datepicker').datetimepicker({
        format: 'YYYY-MM-DD HH:mm:ss'
      });
    });
  </script>

  <div class="row">
    <div class="col-sm-6">
      <div class="group"><h2>Edit Question</h2></div>

      <form class="simple_form edit_todo" id="edit_todo" novalidate="novalidate" action="<%= "/todolists/#{params[:id]}" %>" accept-charset="UTF-8" method="post">
        <input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="_method" value="patch">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <div class="form-group text required todo_content form-group-valid">
          <label class="text required" for="todo_content">Content <abbr title="required">*</abbr></label>
          <textarea class="form-control is-valid text required" name="todo[content]" id="todo_content">Default Content</textarea>
        </div>
        <div class="form-group select optional todo_priority form-group-valid">
          <label class="select optional" for="todo_priority">Priority</label>
          <select class="form-control is-valid select optional" name="todo[priority]" id="todo_priority">
            <option selected="selected" value="0">low</option>
            <option value="1">medium</option>
            <option value="2">high</option>
            <option value="3">urgent</option>
          </select>
        </div>

        <div class="input-group" data-target-input="nearest">
          <input id="complete_time" class="form-control datepicker" data-target="#complete_time" type="text" name="todo[complete_time]">
            <div class="input-group-append" data-target="#complete_time" data-toggle="datetimepicker">
              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
            </div>
        </div>

        <input type="submit" name="commit" value="Submit" data-disable-with="Submitting..." class="btn btn-primary">
        <a class="btn" href="/todolists">Back</a>
      </form>
    </div>

    <div class="col-sm-6"></div>
  </div>
</div>

app/views/assignment/todolists/index.html.erb
<% content_for :page_title,  "TODO" %>

<div class="container-fluid">
  <h4><%= link_to t('todolist.add_todo') , new_todolist_path %></h4>
  <h1><%= t('todolist.all_todo') %></h1>
  <table class="table">
    <thead>
      <tr>
        <td><%= t('todolist.status') %></td>
        <td><%= t('todolist.content') %></td>
        <td><%= t('todolist.complete_time') %></td>
        <td><%= t('todolist.priority') %></td>
        <td><%= t('todolist.action') %></td>
      </tr>
    </thead>
    <tbody>
      <% @todos.each do |todo| %>
      <tr>
        <td>
          <% if todo.status == false %>
            <%= link_to t('todolist.undone'), status_todolist_path(todo), remote: true, class: 'btn btn-danger btn-sm', id: "btn-#{todo.id}" %>
          <% else %>
            <%= link_to t('todolist.done'), status_todolist_path(todo), remote: true, class: 'btn btn-success btn-sm', id: "btn-#{todo.id}" %>
          <% end %>
        </td>
        <td><%= todo.content %></td>
        <td><%= complete_time(todo.complete_time) %></td>
        <td><%= todo.priority %></td>
        <td>
          <%= link_to (fa_icon "eye"), todolist_path(todo), class: 'btn' %>
          <%= link_to (fa_icon "edit"), edit_todolist_path(todo), class: 'btn' %>
          <%= link_to (fa_icon "trash"), todolist_path(todo), class: 'btn', method: :delete %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <script>

  </script>
</div>

app/views/assignment/todolists/new.html.erb
<% content_for :page_title,  "assignment: New" %>

<script>
  $(function () {
    $('.datepicker').datetimepicker({
      format: 'YYYY-MM-DD HH:mm:ss'
    });
  });
</script>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <div class="group"><h2>建立新清單</h2></div>

      <form class="simple_form new_todo" id="new_todo" novalidate="novalidate" action="/todolists" accept-charset="UTF-8" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <div class="form-group text required todo_content">
          <label class="text required" for="todo_content">Content <abbr title="required">*</abbr></label>
          <textarea class="form-control text required" name="todo[content]" id="todo_content">Default Content</textarea>
        </div>
        <div class="form-group select optional todo_priority form-group-valid">
          <label class="select optional" for="todo_priority">Priority</label>
          <select class="form-control is-valid select optional" name="todo[priority]" id="todo_priority"><option selected="selected" value="0">low</option>
            <option value="1">medium</option>
            <option value="2">high</option>
            <option value="3">urgent</option>
          </select>
        </div>
        <div class="input-group" data-target-input="nearest">
          <input id="complete_time" class="form-control datepicker" data-target="#complete_time" type="text" name="todo[complete_time]">
          <div class="input-group-append" data-target="#complete_time" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>

        <input type="submit" name="commit" value="Submit" data-disable-with="Submitting..." class="btn btn-primary">
        <a class="btn" href="/todolists">Back</a>
      </form>
    </div>

    <div class="col-sm-6"></div>
  </div>
</div>

app/views/assignment/todolists/show.html.erb
<body>
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1 class="mt-4"><%= @todo.content %></h1>
        <p class="lead">
          by
          <a href="#"><%#= User.find_by(id: @todo.user_id).username.capitalize %></a>
        </p>
        <hr>
        <p>Posted on <%= @todo.created_at.to_s[0..-4] %></p>
        <% if @todo.status == false %>
          <%= link_to  t('todolist.undone'), status_todolist_path(@todo), remote: true, class: 'btn btn-danger btn-sm', id: "btn-#{@todo.id}" %>
        <% else %>
          <%= link_to  t('todolist.done'), status_todolist_path(@todo), remote: true, class: 'btn btn-success btn-sm', id: "btn-#{@todo.id}" %>
        <% end %>
        <hr>
        <p class="lead"><%= @todo.priority %></p>
        <hr>
        <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">Open Modal</button>
      </div>
      </div>
    </div>
  </div>
</body>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" style="color:#737373;font-style:italic">Modal Header</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <% if @todo.status == false %>
          <%= link_to  t('todolist.undone'), status_todolist_path(@todo), remote: true, class: 'btn btn-danger btn-sm', id: "btn-#{@todo.id}" %>
        <% else %>
          <%= link_to  t('todolist.done'), status_todolist_path(@todo), remote: true, class: 'btn btn-success btn-sm', id: "btn-#{@todo.id}" %>
        <% end %>

        <h5 class="mt-4">
          <%= @todo.content %>
        </h5>
        <p class="lead">Priority: <%= @todo.priority %></p>
        <p>Posted on <%= @todo.created_at.to_s[0..-4] %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/assignment/todolists/status.js.erb
var status = "<%= @todo.status %>";

if( status == 'false' ){
  $("#btn-<%= @id %>")[0].innerHTML = ("<%= t('todolist.undone') %>");
  $("#btn-<%= @id %>").removeClass('btn-success');
  $("#btn-<%= @id %>").addClass('btn-danger');
}else{
  $("#btn-<%= @id %>")[0].innerHTML = ("<%= t('todolist.done') %>");
  $("#btn-<%= @id %>").removeClass('btn-danger');
  $("#btn-<%= @id %>").addClass('btn-success');
}