config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount Blazer::Engine, at: "blazer"

  root 'admin/lab_forum#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :names, only: [:create]
    end
  end

  scope "(:locale)", locale: /en|zh-TW/ do
    devise_for :users

    # 慣例：名字後須 +s
    scope module: 'admin' do
      resources :lab_forum do
        resources :comments
        get 'status', on: :member

        resources :likes, only: [:create]
      end
    end

    root 'lab_forum#index'

    scope module: 'assignment' do
      # resources :todolists do
      #   get 'status', on: :member
      # end

      # https://stackoverflow.com/questions/19189415/how-may-two-routes-with-different-http-request-types-share-the-same-name
      get "/todolists/:id/status", to: "todolists#status", as: "status_todolist"
      get  "/todolists", to: "todolists#index", as: "todolists"
      post "/todolists", to: "todolists#create"
      get  "/todolists/new", to: "todolists#new", as: "new_todolist"
      get  "/todolists/:id/edit", to: "todolists#edit", as: "edit_todolist"
      get  "/todolists/:id", to: "todolists#show", as: "todolist"
      patch "/todolists/:id", to: "todolists#update"
      delete "/todolists/:id", to: "todolists#destroy"

      root 'todolists#index', to: ""
    end

    # constraints subdomain: 'admin' do
    #   scope module: 'admin' do
    #     resources :lab_forum do
    #       resources :comments
    #       get 'status', on: :member
    #     end
    #     root 'lab_forum#index'
    #   end
    # end

    # constraints subdomain: 'assignment' do
    #   scope module: 'assignment' do
    #     resources :todolists
    #     root 'todolists#index'
    #   end
    # end

    # 高見龍老師的範例
    get 'bmi', to: "bmi#index"
    post 'bmi', to: "bmi#result"

    # get, post自己寫
    get 'name', to: "name#index"
    post 'name', to: "name#post_result"
    get 'username', to: "name#get_result"

    # 靜態網頁
    get 'card', to: "card#show"

    # sinatra (先放著)
    # mount Api::Ping => '/api/ping'

    # 寫在最後一行
    # 基本routes應用：https://railsbook.tw/chapters/11-routes.html
    get "/:single_page" , to: "staticpages#show", as: 'page'
  end
end

app/views/layouts/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(45).jpg"
        alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(46).jpg"
        alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(47).jpg"
        alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-3 bg-dark fixed-bottom">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; HanTing's Website 2019</p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="<%= lab_forum_index_path %>"><%= t('navbar.hans_web') %></a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item"><a class="nav-link" href="<%= page_path('home') %>"><%= t('navbar.home') %></a></li>
    <li class="nav-item"><a class="nav-link" href="<%= lab_forum_index_path %>"><%= t('navbar.lab_forum') %></a></li>
    <li class="nav-item"><a class="nav-link" href="<%= todolists_path %>"><%= t('navbar.todo') %></a></li>

    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        <%= t('navbar.pages') %>
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="<%= page_path('todo') %>"><%= t('navbar.todo_daily') %></a>
        <a class="dropdown-item" href="<%= page_path('jsbasic') %>"><%= t('navbar.ajax_basic') %></a>
        <a class="dropdown-item" href="<%= page_path('lotto') %>"><%= t('navbar.lotto') %></a>
        <a class="dropdown-item" href="<%= page_path('squared') %>"><%= t('navbar.squared_up') %></a>
        <a class="dropdown-item" href="<%= bmi_path %>"><%= t('navbar.bmi_cal') %></a>
        <a class="dropdown-item" href="<%= name_path %>"><%= t('navbar.name_form') %></a>
        <a class="dropdown-item" href="<%= page_path('help') %>"><%= t('navbar.help') %></a>
      </div>
    </li>
  </ul>

  <ul class="navbar-nav ml-auto">
    <%#= content_tag :li do %>
      <%#= link_to 'Switch to English', locale: :en %>
    <%# end unless current_page?(locale: :en) %>

    <%#= content_tag :li do %>
      <%#= link_to 'Switch to Taiwanese', locale: :"zh-TW" %>
    <%# end unless current_page?(locale: :"zh-TW") %>

    <%#= link_to "中文版", action: :set_locale, locale: "zh-TW" %>
    <%#= link_to "English", action: set_locale, locale: "en" %>
    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
      <%= t('navbar.account') %>
    </a>
    <div class="dropdown-menu  dropdown-menu-right">
      <% if current_user %>
        <%= link_to t('navbar.logout'), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      <% else %>
        <a class="dropdown-item" href="<%= new_user_registration_path %>"><span class="fa fa-user"></span><%= t('navbar.signup') %></a>
        <a class="dropdown-item" href="<%= new_user_session_path %>"><span class="fa fa-sign-in"></span><%= t('navbar.login') %></a>
      <% end %>
    </div>
  </ul>

  <ul class="navbar-nav text-right">
    <%= content_tag :li do %>
      <li class="nav-item"><%= link_to 'English', { locale: :en }, class: "nav-link" %></li>
    <% end unless current_page?(locale: :en) %>
    <%= content_tag :li do %>
      <li class="nav-item"><%= link_to '繁體中文', { locale: :"zh-TW" }, class: "nav-link" %></li>
    <% end unless current_page?(locale: :"zh-TW") %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : 'Side Project' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
    <%= favicon_link_tag asset_path('diary.ico') %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render 'layouts/carousel' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%#= render "layouts/footer" %>
  </body>
</html>